### ISSUE TITLE
Organise files to get ready for github integration

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#1]
At our next meeting, we'll set up a proper file and Git management system so we can share and update our code.

In preparation for this please organise the data and code using the following format (where \ indicates a folder)

```
readme.txt      # A readme file (can be blank for now)
\data                # raw data in .txt, .RData, .rds files
\R                     # .R files
\rmds               # markdown files
eegoals.Rproj  # An Rproject file
```
For example...

![image](https://cloud.githubusercontent.com/assets/8480980/24091967/c51532a2-0d4b-11e7-9b6a-a2b6e4ef1e90.png)

Only include files that are necessary. At our next meeting, I'll show you a few tricks to avoid working directory issues that will then allow us both to always update and run the code without problems.

**Comment by mdsteiner** [comment]
done.
