### ISSUE TITLE
New references

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#14]
- Ventromedial Prefrontal Cortex Encodes a Latent Estimate of Cumulative Reward: http://www.sciencedirect.com/science/article/pii/S089662731631011X (recommended by Todd Hare)

**Comment by mdsteiner** [comment]
Yesterday Christopher Summerfield gave a talk in the colloquium. I also immediately thought that this might be relevant to consider. I havent read the paper yet, but from what he said in the presentation this might also be relevant: http://www.pnas.org/content/113/11/3102

**Comment by ndphillips** [comment]
Haha, what a coincidence. Yes let's keep these papers in mind and at the very least cite them.
