### ISSUE TITLE
Post experiment surveys

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#17]
- Use same questions from pilot study.
- Add additional question asking if they tried to cheat at all (e.g.; look at code). If so, please tell us and we will still pay you but won't use your data for scientific research.
- Ask if they used calculator or any tool.
- Have you played a similar task as this one on the mturk?
- How did you find this HIT? Options: Searched on mturk, discovered on an external website or messenger board, Other.

**Comment by mdsteiner** [comment]
I included the following question after the last game they play. Do you also think that it makes sense to ask about their belief about the distributions?

![grafik](https://cloud.githubusercontent.com/assets/26483702/25340763/06043502-2907-11e7-9eee-dc2122bc6d6f.png)

Another thing I wondered was whether to include a risk propensity scale or not.

**Comment by ndphillips** [comment]
Sure! Add this, it sounds interesting!

Another way to phrase it:

You may have noticed that in each game, there was one option with a larger variability of outcomes, and one option with a smaller variability. Do you think one of these options had, on average, better points than the other?

A) I think the option with the higher point variability also had higher values on average.
B) I think the option with the lower point variability had higher values on average.
C) I think both options gave the same number of points on average.

**Comment by ndphillips** [comment]
@mdsteiner It looks like you haven't included the additional surveys from the pilot. Can you include these?

**Comment by mdsteiner** [comment]
they should be in the goalQuestionnaire_app.R and noGoalQuestionnaire_app.R files in the apps folder.
I did it already in separate apps to make sure that the load is spread to several apps...

**Comment by ndphillips** [comment]
Ah got it, do you really think it's necessary to create separate apps? Seems not very elegant. How would this work for the participant? They click a link at the end of the main app that takes them to a new site that they then type their workerid again in? If possible, I think it would be much better to have it as one app...

**Comment by mdsteiner** [comment]
yes I think we need to do this... I also had this in the pilot study and we still had the crashes.
You can assign a weblink to a button. And the end of the games they just click the 'next' button and are then linked to the second app. But of course you then have the grey screen that says disconnect and then it loads the new app... 
And yes they enter their workerid again in the second app...

**Comment by ndphillips** [comment]
Even with the javascript version of the app it still crashes if we include the questionnaire within the main app? If so, this is just really bad...

Of course if we need to, we can split the game and questionnaire between two apps, but I just don't see why it is still so crash prone...
