### ISSUE TITLE
Include pre-game comprehension check (?)

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#19]
Not totally necessary but could be helpful.

Include a post-instructions, pre-game compehension check.

Eg..

(In the goal condition)
1)  WHat happens if you end a game with more points than the goal?
   a) I earn a flat bonus of 30c for that game.
   b) I earn money for the number of total points I earn, plus a bonus

(in all conditions)
1) Can options substantially change over time?
  a) No, while there is random variation in options, they do not substantially change over time.
  b) Yes, options can substantially change over time.

Others?

If participants fail any of these questions, then send them back to the instructions page. After, they then do the comprehension check again. Make sure to keep track of how many times each person failed.

if someone fails 3 times, then just send them to the study.

**Comment by mdsteiner** [comment]
This might potentially lead to one problem: If we ask them these questions they might just simply try to go back using the browsers return button (although we tell them not to). This would make it look like a crash for us and we would therefore exclude these participants.

**Comment by ndphillips** [comment]
Hmmm, that's true. It might be better just to have a single comprehension check page, and if they fail a question, just give them feedback telling them the correct answer, then move on (no repeat of the instructions or page)
