### ISSUE TITLE
Potential problem with data

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/EE-Goals#21]
I found a potential problem in the data. 

Here are tables of the raw data for condition LG (3):

|                      |     | choose | high variance |
|----------------------|-----|--------|---------------|
|                      |     | no     | yes           |
| high variance chosen | no  | 2913   | 866           |
|                      | yes | 509    | 584           |

and for condition HG (4):

|                      |     | choose | high variance |
|----------------------|-----|--------|---------------|
|                      |     | no     | yes           |
| high variance chosen | no  | 1998   | 867           |
|                      | yes | 954    | 1104          |

I'm not sure, maybe that's no problem but when I looked at these tables I thought that the false alarm and false rejection fields should contain much lower numbers than the hit and correct rejection cells. Do you think this might be a problem?

**Comment by ndphillips** [comment]
Can you show me the code you used to generate these tables?

**Comment by mdsteiner** [comment]
I used the table function. Values are either 0 or 1 in both variables. Code is:

df <- readRDS("data/dataTrialLevelPGetthere.rds")
table(df$high.var.chosen[df$condition == 3], df$choose.highvar.subj[df$condition == 3])
table(df$high.var.chosen[df$condition == 4], df$choose.highvar.subj[df$condition == 4])

**Comment by ndphillips** [comment]
k, what do you mean about false alarm and false rejection fields? I'm not quite sure which cells you think should be lower and why

**Comment by mdsteiner** [comment]
Shouldn't the yes/no and no/yes cells contain much lower values than the others (i.e. the topright and bottomleft cells). I mean that they are not 0 is clear, you'd expect some noise but I wasn't sure if it could be a problem that there is no big difference between the yes/no, and no/yes cells and the yes/yes cell. But  of course the predictions which you should choose come from our model, so this could also just mean that we simply need to adapt our model (as we anyway planned). 
Again maybe that's no problem and i was just getting paranoid...^^

**Comment by ndphillips** [comment]
Hmmm, I'm not concerned. Random sampling error + non random sampling behavior (i.e.; hot stove effects) could lead to strange outcomes. But to make yourself feel more comfortable, you might want to look at a few participants' data and make sure that the calculations make sense.
