### ISSUE TITLE
Conduct 'optimal' simulations comparing random, EV max, rsf

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#23]
- Show some simulations showing to what extent random choice, EV-max, and rsf perform in different environments. You can do this by adding a `strategy = "random"` to the simulation design matrix. Then, when this argument is passed to `rl.sim.fun()`, make sure the strategy always chooses randomly, e.g.; by using `selection.strat = "softmax"` and `theta = 0`.
- Then, in all plots showing differences between success of EV-max and rsf, include a random model for comparison.

**Comment by mdsteiner** [comment]
I might have overdone things a bit. I ran it with 15000 simulations to be really sure. I used the egreedy  selection strategy (epsilon = .2, alpha = .3) and the environments with high mean = 4, low mean = 2.5, high sd = 11, low sd = 2.5. 
The goal was reached in 39% of the cases. Here are the plots:

![grafik](https://cloud.githubusercontent.com/assets/26483702/25784109/73d40dee-3368-11e7-9fb8-eb8ff84b352d.png)


![grafik](https://cloud.githubusercontent.com/assets/26483702/25784111/7dbc85a2-3368-11e7-9f77-483e7fb29d1f.png)


![grafik](https://cloud.githubusercontent.com/assets/26483702/25784115/8816f10e-3368-11e7-9794-2f0ea95989d1.png)


![grafik](https://cloud.githubusercontent.com/assets/26483702/25784121/913bb1de-3368-11e7-8ec8-53b58ab65224.png)


![grafik](https://cloud.githubusercontent.com/assets/26483702/25784134/9a225636-3368-11e7-964b-e5fbb2a54c27.png)

**Comment by ndphillips** [comment]
Looks good!
One minor suggestion - In all future plots, try to come up with environment labels that are somewhat interpretable. E.g.; Sm = same mean, HmHv (high mean = high variance), HmLv (high mean = low variance). Or something like that.
