### ISSUE TITLE
In the simulation(s), how often do rsf and ev make different choice predictions?

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#24]
- Calculate, for each trial, what the predicted choice would be of RSF and EV-max for the next trial.
- Note, this will take some programming, because the simulation currently assumes people are using one of these strategies. Therefore, you'll have to add extra code for *all* strategies, saying, "well, IF this person then switched to strategy X, what would the prediction be." Then save the predictions for both strategies, see if they are the same or not, and store in a vector.

**Comment by mdsteiner** [comment]
Predictions between rsf and ev differ in around 47.6% of the cases. (Obtained with egreedy, epsilon = .2, alpha = .3 and the environments with the means and sds described for the new study design, i.e. high mean = 4, low mean = 2.5, high sd = 11, low sd = 2.5)

![grafik](https://cloud.githubusercontent.com/assets/26483702/25784091/34540c50-3368-11e7-8567-0694d8281228.png)

**Comment by ndphillips** [comment]
Cool. Just to be clear, the different strategies in this plot represent different generating processes right? In other words, the RSF data is how often data generated by a true RSF strategy would have been predicted differently by an RSF versus EV strategy, while the EV data is the same but generated by a true EV strategy? Is this correct?

**Comment by mdsteiner** [comment]
Yes exactly, that's correct.
