### ISSUE TITLE
Predictions for pre-registration

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#25]
### Prediction 1 (strategy use)

*Here, we are making a bold claim that people will act like risk sensitive foragers*
- When there is a difference between the RSF prediction and the EV max prediction, then people will be more likely to choose the rsf prediction.

### Prediction 1B (selecting high variance option relative to the goal)
*Here we predict that people on average will act like rsf*
- When people are above a goal, they are less likely to select high variance options than when they are below a goal.
 

### Prediction 2 (efficacy of strategy use)

*Here we make the claim that people who make selections more like risk sensitive foragers should do better than those who behave less like risk sensitive foragers*

- The more people's choices are consistent with RSF predictions (when they differ from EV), the more likely they are to reach the goal. For example, if there are 10 trials where predictions differ, and participant A selects the RSF favorable option on 8 / 10 trials, then this person should be more likely to reach the goal than a participant B who selects the RSF favorable option on only 2 / 10 trials.

**Comment by mdsteiner** [comment]
I added them to the preregistration form and also to the analysis script.
