### ISSUE TITLE
Several updates to experiment prior to running pilot

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#27]
- I just pushed several updates to the `javaBanditGoal_app.R` and `javaBanditNoGoal_app.R` that change some wordings and emphases.

-  Please test the games and make sure I didn't screw anything up with the central programming. I'm afraid I may have screwed up the action when clicking boxes for the no-goal condition.

**Comment by mdsteiner** [comment]
I found the bug ind the no-goal condition and fixed it. Thanks for the changes! I think the payout structure in the no-goal condition is really cool when it is so transparent what point value gives you what outcome. This makes it really painful when you're playing and getting high losses.
