### ISSUE TITLE
Simple "model" comparison between 2 heuristic models

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#3]
Contrast 2 simple heuristic choice models.

1) Always select high sample mean option
2) Select option favored by RSF

For each participant at each trial, calculate the prediction from each model and compare to the participant's actual choice.

- In what percent of trials do models 1 and 2 differ in their predictions?
- For how many participants does model 2 outperform model 1?
- Does model 2 outperform model 1 when people are closer to the goal?

**Comment by mdsteiner** [comment]
I addressed this issue in 03_issue3.R. Here are the findings:
- The two models differ in 49.5% of the cases
- The RSF model outperforms the high sample mean model in 7% of the participants. It is outperformed in 91% of participants.
- RSF does not outperform the other models when people are closer to the goal.


![grafik](https://cloud.githubusercontent.com/assets/26483702/24462482/5c8554aa-14a4-11e7-86a6-621847d27790.png)
