### ISSUE TITLE
Create plot showing relationship between strength of evidence of strategies and choice proportions

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#31]
Create a plot showing the relationship between how much the two strategies (rsf v. ev) favor an option, and how likely it was to be chosen by participants.

e.g.

for RSF, you can calculate the probability that optionA vs. optionB gets you to the goal. Then calculate the difference. As a function of this difference, how likely are people to choose the option favored by RSF?

For EV, you could do a d-prime on the two distributions. e.g.; mean(a) / sd(a) - mean(b) / sd(b). The more extreme the d-prime, the more people should choose the option with the higher mean

**Comment by mdsteiner** [comment]
For the RSF model the curve has the shape we expect it to have:

![grafik](https://user-images.githubusercontent.com/26483702/28259824-78c36802-6ad8-11e7-8b8d-afd28929a5d7.png)

Also for the EV mode. in the goal condition (note that d primes are rounded to whole numbers to have large enoug batches to get a more or less smooth curve):

![grafik](https://user-images.githubusercontent.com/26483702/28259878-b8452506-6ad8-11e7-8fbc-42d07f28d6ad.png)

But for the No Goal condition there does not seem to be a relation (or actually a strange one) between d primes and probability of choosing option 1:

![grafik](https://user-images.githubusercontent.com/26483702/28259901-e52990d4-6ad8-11e7-89a2-6cff65194abb.png)

**Comment by ndphillips** [comment]
Interesting plots! I especially like the first one for the RSF condition.

Can you re-run these plots with the following change

1) Group the data by creating X bins (e.g.; 10) on the x-axis and show mean values on the y-axis. This should greatly smooth out the plots. Also, consider indicating how much data was in each bin, perhaps by plotting the size of the points as a function of the number of samples.

![image](https://user-images.githubusercontent.com/8480980/28260200-364d164c-6ada-11e7-86ea-6b307e4679b9.png)

**Comment by mdsteiner** [comment]
So I rerun the plots. I printed the proportion of the samplesize used in each bin on top of the points to make it clear. All plots show heavy clustering near evidence strength 0...

RSF option:
![grafik](https://user-images.githubusercontent.com/26483702/28265194-d19624cc-6aee-11e7-8df8-5b9738d3a050.png)


EV option, Goal condition:
![grafik](https://user-images.githubusercontent.com/26483702/28265219-ed7f2d82-6aee-11e7-8095-23586703c011.png)

EV option, No Goal condition:
![grafik](https://user-images.githubusercontent.com/26483702/28265238-ff4b7d5e-6aee-11e7-8a9b-b9dd64e15c5f.png)

**Comment by ndphillips** [comment]
Great! The RSF plot for the goal condition looks beautiful. 

Any idea what is causing the strange dip is in the EV plots?  Are these mostly trials in the beginning or end of the game? Something we might want to explore later. But not critical at this point so I'll close the issue.
