### ISSUE TITLE
Study 1 Analysis: Learning over games

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#33]
I just told Jana about our great results, and one question she asked was if people do better as they get experience over games. For example, 

- Are people in the goal condition more likely to reach the goal on the last game than the first game? 
- In the EV condition, do people earn more points in later games than early games?
- Do people in the goal condition act more in an RSF way in later games than early games?

Not critical analyses but would I think they would be interesting to see in a plot. If you push the latest results to GitHub I can run the analyses too :)

**Comment by mdsteiner** [comment]
Short form: No big learning effects over games.
Here are some plots:

***Are people in the goal condition more likely to reach the goal on the last game than the first game?***
![grafik](https://user-images.githubusercontent.com/26483702/28248430-f3916488-6a44-11e7-81d0-4d8a0f6a9145.png)

It seems as though there was some learning over games, but the effect is quite small.

***In the No Goal condition, do people earn more points in later games than early games?***

![grafik](https://user-images.githubusercontent.com/26483702/28248445-2a19fe0c-6a45-11e7-9c9c-84f722026bb9.png)

or as pirateplot to have distribution info:

![grafik](https://user-images.githubusercontent.com/26483702/28248452-39999112-6a45-11e7-899a-b38ae4970208.png)

It doesn't seem as though they would learn much over games, or if they do it does not really affect the total points.

***Do people in the goal condition act more in an RSF way in later games than early games?***
![grafik](https://user-images.githubusercontent.com/26483702/28248478-79fc2f12-6a45-11e7-8ed0-c8bdee9df33f.png)

or as pirateplot to have distribution info:

![grafik](https://user-images.githubusercontent.com/26483702/28248520-13f3a1e0-6a46-11e7-89ec-7b90dec4a229.png)


to do this I just averaged the RSF accuracy rates over participants... Again no effects...

**Comment by ndphillips** [comment]
Looks good, thanks!
