### ISSUE TITLE
Check behavior of participants separated whether they indicated that they followed an EV or an RSF strategy.

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/EE-Goals#40]
Look at prediction accuracy values for RSF and EV and if they are higher for the people who indicated that they would follow the respective strategy.

Another approach would be to fit the data to the models we used to simulate the data and then check for each participant which model better predicts the behavior and see whether this matches the stategy indicated by them.

**Comment by mdsteiner** [comment]
If for each model we compare the mean prediction accuracies for participants who indicated that they followed this respective strategy vs. the participants who followed the other strategy we see some differences that include .50 (i.e. the one consistent with the model are above .5, the others below). Comparing the values with a chi squared test showed no significance... I added it to the markdown file. I also added a floating table of contents so navigation is a bit easier...

**Comment by ndphillips** [comment]
got it, thanks! I guess that means either the model isn't capturing the true strategy, or the questionnaire is useless...
