### ISSUE TITLE
Power Analysis

### ISSUE THREAD

**Issue by mdsteiner** [ndphillips/EE-Goals#41]
Apparently the psych science guys want to have a power analysis so I'll try to come up with something.

**Comment by ndphillips** [comment]
Good to know. See what you can do but keep this as a relatively low priority.

**Comment by mdsteiner** [comment]
I found an R package called simr that can run power analyses for all the models from lmer and glmer functions from the lme4 package. It uses Monte Carlos simulations and you can also create power curves with it... I'll add it to the rpubs file once I have run the analyses...

**Comment by ndphillips** [comment]
cool!

**Comment by mdsteiner** [comment]
I will add this later, I found out that it takes several hours to run for the simulations for only one model, so I will use one of our lab computers for this and let it run for some days...

**Comment by ndphillips** [comment]
damn. that sucks. Can you do a test run on a subset of the data (like 50 participants) to get an idea of the results?

**Comment by mdsteiner** [comment]
I ran the analysis for the model we specified in the pilot study with the 23 participants we had there and this had a power of 22% or so... But with our actual data I don't know a straightforward way to estimate it with a lower number but with the same effect. But I've set up the analyses on two of our lab computers and will let them run for the next few days and then we'll know more...

**Comment by mdsteiner** [comment]
Power analysis and confidence intervall estimation is done (took around a week to run it on two computers). I'll add the results in the overleaf file...
