### ISSUE TITLE
How does behavior change from game 1 to game 5?

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#5]
I know @mdsteiner  analysed this before, but I forgot the results.

- Do variables such as points earned, proportion of reaching the goal, switch rates (etc.) change consistently across games from game 1 to game 5?

**Comment by mdsteiner** [comment]
I adressed this issue in 04_issue5.R 
These are the findings:

- Points earned do not systematically change over games
- Switch rates decrease over games
- Median response times decreased over games
- Proportion of high EV chosen tends to slightly increase over games
- Proportion of high variance option chosen tends to increase in the high EV is high variance conditions and to decrease in the high EV is low variance condition
- Proportion of participants who reached the goal does not systematically change over games

*Points earned do not systematically change over games*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490001/cb8db9c4-1520-11e7-9d92-76c4d131d7da.png)

*Switch rates decrease over games:*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490039/0a0dfe3e-1521-11e7-93b8-65864cb9455e.png)

*Median response times decrease over games:*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490067/20837d88-1521-11e7-89f6-e19ae7ee7ed9.png)

*Proportion of high EV chosen tends to slightly increase over games:*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490098/4c26f078-1521-11e7-99f5-50b18e41b505.png)

*Proportion of high variance option chosen tends to increase in the high EV is high variance conditions and to decrease in the high EV is low variance condition:*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490144/8c5c4954-1521-11e7-8de2-0f2b9887ad9d.png)

*Proportion of participants who reached the goal does not systematically change over games:*
![grafik](https://cloud.githubusercontent.com/assets/26483702/24490418/cb9c827c-1522-11e7-83a1-a0c81b3f57d4.png)
