### ISSUE TITLE
Add .csv files to data folder without workerids

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/EE-Goals#9]
Please add .csv files for each participant in the data folder, but replace workerids with a randomized value.

**Comment by mdsteiner** [comment]
I added .txt files. csv caused problems with the strign variables...

**Comment by ndphillips** [comment]
Great! Thanks!

One note. As a general rule, the person that opens the issue should close it. This helps to ensure that the task is indeed completed according to the issue poster’s true intensions (which in each case so far it has!).

It also just helps the workflow in case the poster misses the email stating that it was closed.

Nathaniel





# ———————————
Nathaniel D. Phillips, PhD
Economic Psychology, University of Basel
nathaniel.phillips@unibas.ch<mailto:nathaniel.phillips@unibas.ch>
ndphillips.github.io<http://ndphillips.github.io>

On 31 Mar 2017, at 09:09, mdsteiner <notifications@github.com<mailto:notifications@github.com>> wrote:


I added .txt files. csv caused problems with the strign variables...
